
package Client.View;

import static Game.Game.SQUARE;
import javax.swing.JLabel;

public class GameDisplay extends javax.swing.JFrame {
    public JLabel[][] displayBoardPlayer = new JLabel[SQUARE][SQUARE];
    public JLabel[][] displayBoardEnemy = new JLabel[SQUARE][SQUARE];

    public GameDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBG = new javax.swing.JPanel();
        jPanel_BGHeaderEnemy = new javax.swing.JPanel();
        jLabel_EnemyHeader = new javax.swing.JLabel();
        jPanel_BGBoard = new javax.swing.JPanel();
        jPanel_BGEnemy = new javax.swing.JPanel();
        jPanel_BGMenu = new javax.swing.JPanel();
        jComboBox_Tokens = new javax.swing.JComboBox<>();
        jCheckBox_Place = new javax.swing.JCheckBox();
        jCheckBox_Connect = new javax.swing.JCheckBox();
        jCheckBox_Disconnect = new javax.swing.JCheckBox();
        jLabelM = new javax.swing.JLabel();
        jLabel_I = new javax.swing.JLabel();
        jLabel_Money = new javax.swing.JLabel();
        jLabel_Iron = new javax.swing.JLabel();
        jButton_Rotate = new javax.swing.JButton();
        jLabel_I1 = new javax.swing.JLabel();
        jLabel_CurrentShield = new javax.swing.JLabel();
        jButton_Shield = new javax.swing.JButton();
        jPanel_BGSelection = new javax.swing.JPanel();
        jButton_Ready = new javax.swing.JButton();
        jButton_Enemy1 = new javax.swing.JButton();
        jButton_Enemy2 = new javax.swing.JButton();
        jButton_Enemy3 = new javax.swing.JButton();
        jButton_Enemy4 = new javax.swing.JButton();
        jLabel_W = new javax.swing.JLabel();
        jLabel_Weapon = new javax.swing.JLabel();
        jPanel_Chat = new javax.swing.JPanel();
        jTextField_Chat = new javax.swing.JTextField();
        jButton_Send = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Chat = new javax.swing.JTextArea();
        jPanel_BGActivity = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Activity = new javax.swing.JTextArea();
        jPanel_BGRefresh = new javax.swing.JPanel();
        jButton_Refresh = new javax.swing.JButton();
        jPanel_BGHeaderBoard = new javax.swing.JPanel();
        jLabel_EnemyHeader1 = new javax.swing.JLabel();
        jPanel_BGHeaderMenu = new javax.swing.JPanel();
        jButton_Info = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1700, 940));

        jPanelBG.setBackground(new java.awt.Color(54, 141, 197));
        jPanelBG.setMaximumSize(new java.awt.Dimension(1600, 940));
        jPanelBG.setMinimumSize(new java.awt.Dimension(1600, 940));

        jPanel_BGHeaderEnemy.setBackground(new java.awt.Color(54, 141, 197));
        jPanel_BGHeaderEnemy.setMaximumSize(new java.awt.Dimension(1718, 40));
        jPanel_BGHeaderEnemy.setMinimumSize(new java.awt.Dimension(1718, 40));
        jPanel_BGHeaderEnemy.setPreferredSize(new java.awt.Dimension(1718, 40));

        jLabel_EnemyHeader.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_EnemyHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel_BGHeaderEnemyLayout = new javax.swing.GroupLayout(jPanel_BGHeaderEnemy);
        jPanel_BGHeaderEnemy.setLayout(jPanel_BGHeaderEnemyLayout);
        jPanel_BGHeaderEnemyLayout.setHorizontalGroup(
            jPanel_BGHeaderEnemyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGHeaderEnemyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_EnemyHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_BGHeaderEnemyLayout.setVerticalGroup(
            jPanel_BGHeaderEnemyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGHeaderEnemyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_EnemyHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_BGBoard.setBackground(new java.awt.Color(16, 111, 124));
        jPanel_BGBoard.setMaximumSize(new java.awt.Dimension(700, 700));
        jPanel_BGBoard.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanel_BGBoard.setPreferredSize(new java.awt.Dimension(700, 700));

        javax.swing.GroupLayout jPanel_BGBoardLayout = new javax.swing.GroupLayout(jPanel_BGBoard);
        jPanel_BGBoard.setLayout(jPanel_BGBoardLayout);
        jPanel_BGBoardLayout.setHorizontalGroup(
            jPanel_BGBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel_BGBoardLayout.setVerticalGroup(
            jPanel_BGBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jPanel_BGEnemy.setBackground(new java.awt.Color(153, 153, 153));
        jPanel_BGEnemy.setMaximumSize(new java.awt.Dimension(700, 700));
        jPanel_BGEnemy.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanel_BGEnemy.setPreferredSize(new java.awt.Dimension(700, 700));

        javax.swing.GroupLayout jPanel_BGEnemyLayout = new javax.swing.GroupLayout(jPanel_BGEnemy);
        jPanel_BGEnemy.setLayout(jPanel_BGEnemyLayout);
        jPanel_BGEnemyLayout.setHorizontalGroup(
            jPanel_BGEnemyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel_BGEnemyLayout.setVerticalGroup(
            jPanel_BGEnemyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jPanel_BGMenu.setBackground(new java.awt.Color(54, 141, 197));
        jPanel_BGMenu.setMaximumSize(new java.awt.Dimension(150, 700));
        jPanel_BGMenu.setMinimumSize(new java.awt.Dimension(150, 700));
        jPanel_BGMenu.setPreferredSize(new java.awt.Dimension(150, 700));

        jComboBox_Tokens.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jCheckBox_Place.setBackground(new java.awt.Color(54, 141, 197));
        jCheckBox_Place.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCheckBox_Place.setText("Place");

        jCheckBox_Connect.setBackground(new java.awt.Color(54, 141, 197));
        jCheckBox_Connect.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCheckBox_Connect.setText("Connect");

        jCheckBox_Disconnect.setBackground(new java.awt.Color(54, 141, 197));
        jCheckBox_Disconnect.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCheckBox_Disconnect.setText("Disconnect");

        jLabelM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelM.setText("Money");

        jLabel_I.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_I.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_I.setText("Iron");

        jLabel_Money.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Money.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_Iron.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_Iron.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton_Rotate.setText("ROTATE");

        jLabel_I1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_I1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_I1.setText("Current Shield");

        jLabel_CurrentShield.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_CurrentShield.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton_Shield.setText("ACTIVATE");

        javax.swing.GroupLayout jPanel_BGMenuLayout = new javax.swing.GroupLayout(jPanel_BGMenu);
        jPanel_BGMenu.setLayout(jPanel_BGMenuLayout);
        jPanel_BGMenuLayout.setHorizontalGroup(
            jPanel_BGMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_BGMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Rotate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Iron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Money, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_I, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_Tokens, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_I1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addGroup(jPanel_BGMenuLayout.createSequentialGroup()
                        .addGroup(jPanel_BGMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox_Place)
                            .addComponent(jCheckBox_Connect)
                            .addComponent(jCheckBox_Disconnect))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton_Shield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel_CurrentShield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_BGMenuLayout.setVerticalGroup(
            jPanel_BGMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Money, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_I, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Iron, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel_I1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_CurrentShield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Shield)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(jComboBox_Tokens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox_Place)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_Connect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_Disconnect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Rotate)
                .addGap(17, 17, 17))
        );

        jPanel_BGSelection.setBackground(new java.awt.Color(54, 141, 197));
        jPanel_BGSelection.setMaximumSize(new java.awt.Dimension(150, 700));
        jPanel_BGSelection.setMinimumSize(new java.awt.Dimension(150, 700));
        jPanel_BGSelection.setPreferredSize(new java.awt.Dimension(150, 700));

        jButton_Ready.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_Ready.setText("READY");

        jButton_Enemy1.setText("1");
        jButton_Enemy1.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton_Enemy1.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton_Enemy1.setPreferredSize(new java.awt.Dimension(100, 100));

        jButton_Enemy2.setText("2");
        jButton_Enemy2.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton_Enemy2.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton_Enemy2.setPreferredSize(new java.awt.Dimension(100, 100));

        jButton_Enemy3.setText("3");
        jButton_Enemy3.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton_Enemy3.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton_Enemy3.setPreferredSize(new java.awt.Dimension(100, 100));

        jButton_Enemy4.setText("4");
        jButton_Enemy4.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton_Enemy4.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton_Enemy4.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel_W.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        jLabel_W.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_W.setText("Current Weapon");

        jLabel_Weapon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_Weapon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Weapon.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel_Weapon.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel_Weapon.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout jPanel_BGSelectionLayout = new javax.swing.GroupLayout(jPanel_BGSelection);
        jPanel_BGSelection.setLayout(jPanel_BGSelectionLayout);
        jPanel_BGSelectionLayout.setHorizontalGroup(
            jPanel_BGSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_BGSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Ready, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BGSelectionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel_BGSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Enemy3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Enemy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Enemy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Enemy4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Weapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel_W, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_BGSelectionLayout.setVerticalGroup(
            jPanel_BGSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BGSelectionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton_Enemy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Enemy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Enemy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Enemy4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel_W)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Weapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton_Ready, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_Chat.setBackground(new java.awt.Color(54, 141, 197));
        jPanel_Chat.setMaximumSize(new java.awt.Dimension(856, 200));
        jPanel_Chat.setMinimumSize(new java.awt.Dimension(856, 200));
        jPanel_Chat.setPreferredSize(new java.awt.Dimension(856, 200));

        jButton_Send.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_Send.setText("SEND");

        jTextArea_Chat.setEditable(false);
        jTextArea_Chat.setColumns(20);
        jTextArea_Chat.setRows(5);
        jScrollPane2.setViewportView(jTextArea_Chat);

        javax.swing.GroupLayout jPanel_ChatLayout = new javax.swing.GroupLayout(jPanel_Chat);
        jPanel_Chat.setLayout(jPanel_ChatLayout);
        jPanel_ChatLayout.setHorizontalGroup(
            jPanel_ChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addGroup(jPanel_ChatLayout.createSequentialGroup()
                        .addComponent(jTextField_Chat, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Send)))
                .addContainerGap())
        );
        jPanel_ChatLayout.setVerticalGroup(
            jPanel_ChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ChatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_ChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Chat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Send))
                .addContainerGap())
        );

        jPanel_BGActivity.setBackground(new java.awt.Color(54, 141, 197));
        jPanel_BGActivity.setMaximumSize(new java.awt.Dimension(855, 200));
        jPanel_BGActivity.setMinimumSize(new java.awt.Dimension(855, 200));
        jPanel_BGActivity.setPreferredSize(new java.awt.Dimension(855, 200));

        jTextArea_Activity.setEditable(false);
        jTextArea_Activity.setColumns(20);
        jTextArea_Activity.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Activity);

        javax.swing.GroupLayout jPanel_BGActivityLayout = new javax.swing.GroupLayout(jPanel_BGActivity);
        jPanel_BGActivity.setLayout(jPanel_BGActivityLayout);
        jPanel_BGActivityLayout.setHorizontalGroup(
            jPanel_BGActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGActivityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_BGActivityLayout.setVerticalGroup(
            jPanel_BGActivityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGActivityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_BGRefresh.setBackground(new java.awt.Color(54, 141, 197));

        jButton_Refresh.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton_Refresh.setText("REFRESH");
        jButton_Refresh.setMaximumSize(new java.awt.Dimension(90, 28));
        jButton_Refresh.setMinimumSize(new java.awt.Dimension(90, 28));
        jButton_Refresh.setPreferredSize(new java.awt.Dimension(90, 28));

        javax.swing.GroupLayout jPanel_BGRefreshLayout = new javax.swing.GroupLayout(jPanel_BGRefresh);
        jPanel_BGRefresh.setLayout(jPanel_BGRefreshLayout);
        jPanel_BGRefreshLayout.setHorizontalGroup(
            jPanel_BGRefreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGRefreshLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_BGRefreshLayout.setVerticalGroup(
            jPanel_BGRefreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BGRefreshLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_BGHeaderBoard.setBackground(new java.awt.Color(54, 141, 197));

        jLabel_EnemyHeader1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_EnemyHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_EnemyHeader1.setText("Your Board");
        jLabel_EnemyHeader1.setToolTipText("");

        javax.swing.GroupLayout jPanel_BGHeaderBoardLayout = new javax.swing.GroupLayout(jPanel_BGHeaderBoard);
        jPanel_BGHeaderBoard.setLayout(jPanel_BGHeaderBoardLayout);
        jPanel_BGHeaderBoardLayout.setHorizontalGroup(
            jPanel_BGHeaderBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGHeaderBoardLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(jLabel_EnemyHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel_BGHeaderBoardLayout.setVerticalGroup(
            jPanel_BGHeaderBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGHeaderBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_EnemyHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_BGHeaderMenu.setBackground(new java.awt.Color(54, 141, 197));

        jButton_Info.setText("INFO");

        javax.swing.GroupLayout jPanel_BGHeaderMenuLayout = new javax.swing.GroupLayout(jPanel_BGHeaderMenu);
        jPanel_BGHeaderMenu.setLayout(jPanel_BGHeaderMenuLayout);
        jPanel_BGHeaderMenuLayout.setHorizontalGroup(
            jPanel_BGHeaderMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGHeaderMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_BGHeaderMenuLayout.setVerticalGroup(
            jPanel_BGHeaderMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BGHeaderMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Info, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelBGLayout = new javax.swing.GroupLayout(jPanelBG);
        jPanelBG.setLayout(jPanelBGLayout);
        jPanelBGLayout.setHorizontalGroup(
            jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBGLayout.createSequentialGroup()
                        .addComponent(jPanel_Chat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_BGActivity, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE))
                    .addGroup(jPanelBGLayout.createSequentialGroup()
                        .addGroup(jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_BGMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_BGHeaderMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_BGHeaderBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_BGBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBGLayout.createSequentialGroup()
                                .addComponent(jPanel_BGHeaderEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel_BGRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelBGLayout.createSequentialGroup()
                                .addComponent(jPanel_BGEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel_BGSelection, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))))
                .addGap(5, 5, 5))
        );
        jPanelBGLayout.setVerticalGroup(
            jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGLayout.createSequentialGroup()
                .addGroup(jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_BGHeaderEnemy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_BGRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_BGHeaderBoard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_BGHeaderMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_BGBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_BGEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_BGMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_BGSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Chat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_BGActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanelBG, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Enemy1;
    public javax.swing.JButton jButton_Enemy2;
    public javax.swing.JButton jButton_Enemy3;
    public javax.swing.JButton jButton_Enemy4;
    public javax.swing.JButton jButton_Info;
    public javax.swing.JButton jButton_Ready;
    public javax.swing.JButton jButton_Refresh;
    public javax.swing.JButton jButton_Rotate;
    public javax.swing.JButton jButton_Send;
    public javax.swing.JButton jButton_Shield;
    public javax.swing.JCheckBox jCheckBox_Connect;
    public javax.swing.JCheckBox jCheckBox_Disconnect;
    public javax.swing.JCheckBox jCheckBox_Place;
    public javax.swing.JComboBox<String> jComboBox_Tokens;
    private javax.swing.JLabel jLabelM;
    public javax.swing.JLabel jLabel_CurrentShield;
    public javax.swing.JLabel jLabel_EnemyHeader;
    public javax.swing.JLabel jLabel_EnemyHeader1;
    private javax.swing.JLabel jLabel_I;
    private javax.swing.JLabel jLabel_I1;
    public javax.swing.JLabel jLabel_Iron;
    public javax.swing.JLabel jLabel_Money;
    private javax.swing.JLabel jLabel_W;
    public javax.swing.JLabel jLabel_Weapon;
    public javax.swing.JPanel jPanelBG;
    public javax.swing.JPanel jPanel_BGActivity;
    public javax.swing.JPanel jPanel_BGBoard;
    public javax.swing.JPanel jPanel_BGEnemy;
    public javax.swing.JPanel jPanel_BGHeaderBoard;
    public javax.swing.JPanel jPanel_BGHeaderEnemy;
    public javax.swing.JPanel jPanel_BGHeaderMenu;
    public javax.swing.JPanel jPanel_BGMenu;
    public javax.swing.JPanel jPanel_BGRefresh;
    public javax.swing.JPanel jPanel_BGSelection;
    public javax.swing.JPanel jPanel_Chat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea jTextArea_Activity;
    public javax.swing.JTextArea jTextArea_Chat;
    public javax.swing.JTextField jTextField_Chat;
    // End of variables declaration//GEN-END:variables
}
